### PR TITLE
Various cherrypickables

### PR DESCRIPTION
**Pull request by sashahart**
It is no problem if you want to just close this, or ignore it: I appreciate that multipart is really quite old, and by now so are these changes to it. Also, this is way too many changes at once, and not all of them will be wanted. But since I was about to delete my fork repo anyway, I wanted to offer this stuff in case any of it is useful, e.g. for cherrypicking or getting ideas. Also, I wanted to offer a hand if you would like any of this to be reworked.

I don't care about attribution or copyright issues, you can have whatever rights you want (edit: to MY changes of course) or my changes can be public domain if any are even useful, I can give whatever documentation would be useful for this.

I have really enjoyed using multipart, thank you for making it and licensing it liberally so that I do not have to deal with cgi.FieldStorage for years now (except when I have to interact with a library that already uses it).

### CODE REVIEW

**Comment by defnull** [comment]
Some of the changes are really nice. I am tempted to just pull all of them.

**Comment by sashahart** [comment]
Maybe it would be worth splitting these out into separate PRs even if they all do eventually come in somehow. I think it is valuable to go slowly. Let me know if you would like me to rebase or edit anything, it's no problem.

**Comment by defnull** [comment]
If you have the time to clean the PRs up a bit I can pull them directly. Perhaps bumping the version to 1.0 to indicate a more complete feature set and the Python 2.5 drop.

**Comment by defnull** [comment]
It has been 9 years now, I think we can close this :)

**Pull request closed without merging**
