### PR TITLE
Adding Gzip content encoding support

### PR DESCRIPTION
**Pull request by another-salad**
This PR adds support for Gzip encoded field data.

Happy to discuss better ways of implementing something like this (which there likely is).

Apologies if I haven't followed any processes, etc before raising this PR.

### CODE REVIEW

**Comment by defnull** [comment]
Is there any real-world client that actually compresses from data?

**Comment by defnull** [comment]
Not sure if this should be handled by a multipart parser. Content encoding can  be handled transparently by an upper layer, e.g. by a WSGI middleware instead.

**Comment by dwheelz** [comment]
Its a use case I have come across in a closed source project. However it doesn't appear to be something that is widely used in other real world applications. If its not appropriate to be handled here then that is fine.

**Comment by defnull** [comment]
Ahh wait, you are implementing this for individual parts, not the entire request? I am only realizing that now. That changes the story a bit. It's still a very rare use-case, but now the multipart parser is definitely the right place to handle that. A WSGI middleware layer would not be able to do that.

**Comment by dwheelz** [comment]
> Ahh wait, you are implementing this for individual parts, not the entire request? I am only realizing that now. That changes the story a bit. It's still a very rare use-case, but now the multipart parser is definitely the right place to handle that. A WSGI middleware layer would not be able to do that. I'll look into it.

Sorry for not being clearer in the PR description. Thanks for looking and the quick responses!

**Comment by defnull** [comment]
I never encountered a client or browser that actually uses per-segment compression, and that feature is also deprectaed (see https://datatracker.ietf.org/doc/html/rfc7578#section-4.7 ). After the massive parser rewrite lately there is no chance that this can be merged. So, I guess, after all these years, we should finally close this issue and move on. Thanks for your work anyway.

**Comment by another-salad** [comment]
> I never encountered a client or browser that actually uses per-segment compression, and that feature is also deprectaed (see https://datatracker.ietf.org/doc/html/rfc7578#section-4.7 ). After the massive parser rewrite lately there is no chance that this can be merged. So, I guess, after all these years, we should finally close this issue and move on. Thanks for your work anyway.

Fair enough, thanks for your time.

**Pull request closed without merging**
